#ifndef EXAMPLES_C_PKG_AMALGAMATE_DISABLE_CONSTANTS_H
#define EXAMPLES_C_PKG_AMALGAMATE_DISABLE_CONSTANTS_H

#define EXAMPLES_C_PKG_AMALGAMATE_DISABLE_BIAS (10)

#ifdef EXAMPLES_FLAG_OFF
#define EXAMPLES_C_PKG_AMALGAMATE_DISABLE_EXTRA (99)

#ifdef EXAMPLES_KEEP_THIS
#define EXAMPLES_C_PKG_AMALGAMATE_DISABLE_NESTED (1)
#endif

#endif

#endif
